In [1]:
import numpy as np
arr1= np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print (arr1.shape)




[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data>3


array([[False, False, False],
       [ True,  True,  True]])

In [3]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data[data > 3]


array([4, 5, 6])